language: php

php:
  - 5.3
  - 5.4

before_script:
  - ./tests/vendor/jackrabbit.sh
  - ./tests/vendor/vendors.php

script: phpunit -c tests/phpunit.xml.dist

notifications:
  irc: "irc.freenode.org#jackalope"
